### ISSUE TITLE
weird build failures under 4.04

### ISSUE THREAD

**Issue by gasche** [ygrek/extunix#15]
opam-builder reports weird extunix build failures on the 4.04 beta:

<http://opam.ocamlpro.com/builder/html/extunix/extunix.0.1.3/a9b8277ed0fa890b4592587b43c5192f>

I have not investigated the issue, but it might be related to <https://github.com/ocaml/ocaml/pull/464> and <https://github.com/ocaml/ocaml/pull/758>.

**Comment by ygrek** [comment]
This failure is caused by introduction of `inline` keyword in ocaml runtime C headers. extunix compiles with std=c89 which apprently doesn't know such keyword. I think it makes sense for extunix to switch to c99

**Comment by ygrek** [comment]
See https://github.com/ocaml/ocaml/commit/d5a6e50e
