### ISSUE TITLE
Build broken on OS X

### ISSUE THREAD

**Issue by mgree** [ygrek/extunix#29]
ExtUnix doesn't build on my computer---nor in [CI](https://travis-ci.org/ygrek/extunix/jobs/512680112). I've been unsuccessful with both OPAM and manual builds. I'm running OCaml 4.0.7.

The problem seems to be one of how ocamlfind is invoked. Simply removing `-syntax camlp4o` doesn't seem to do anything.

```
+ /Users/mgree/.opam/4.07.1+flambda/bin/ocamlfind ocamldep -package bigarray -package bytes -package unix -syntax camlp4o -modules src/pa_have.ml > src/pa_have.ml.depends
ocamlfind: Using -syntax, but no package is selected specifying a preprocessor as required for -syntax
Command exited with code 2.
Compilation unsuccessful after building 79 targets (0 cached) in 00:00:03.
E: Failure("Command ''/Users/mgree/.opam/4.07.1+flambda/bin/ocamlbuild' src/libextunix_stubs.a src/dllextunix_stubs.so src/extunix.cma src/extunix.cmxa src/extunix.a src/extunix.cmxs -tag debug' terminated with error code 10")
make: *** [build] Error 1
```

**Comment by mgree** [comment]
Uninstalling and reinstalling camlp4 did the trick. I have _no_ idea what's going on.

**Comment by ygrek** [comment]
This happened before, true. I don't know the details, would be nice to investigate somehow, otherwise cannot fix

**Comment by mgree** [comment]
I'd be happy to help you investigate, but I'm mostly in the dark about OCaml build systems... and OASIS and its codegen is pretty mystifying to me. So you might need to hold my hand a little in terms of what to try.

I'm pretty surprised that uninstalling and reinstalling camlp4 solved the problem. I only tried it because camlp4 wasn't showing up in `ocamlfind list`. Maybe it's just an OPAM bug?

**Comment by mgree** [comment]
https://discuss.ocaml.org/t/i-cannot-install-extunix-anymore/3699/3?u=mgree seems to confirm my reading that this is an OPAM issue, where camlp4 was left in an indeterminate state.

**Comment by ygrek** [comment]
I see you found that it was camlp4 installed outside of opam. This explains then. I am not sure if extunix is the right place to prevent this, but then I don't know what would be a good solution. Maybe opam people come up with something..

**Comment by mgree** [comment]
I'll come back with whatever I discover, but I think you're right: it's not clear that ExtUnix can do much, though in principle you could write a script to detect the error. If I have the cycles/frustration tolerance, I'll try to see if forking the ocaml-ci-scripts can fix things.

https://github.com/ocaml/opam/issues/2451 seems related, too. The core idea I'm coming to is that after bootstrapping, one wants to signal to the parent package manager that things are installed, but not let it manage _anything_.

**Comment by mgree** [comment]
The current thought is that this is ultimately an issue with `brew`: see https://github.com/Homebrew/homebrew-core/pull/39468. It's not clear why you'd be failing in CI, though... is it possible that Travis is pulling an out-of-date version of brew? I doubt it, per https://github.com/ocaml/ocaml-ci-scripts/blob/4466db9737c1e615d4aab631bb32b3505ea68ce6/.travis-ocaml.sh#L32... let me push a little harder on this.

**Comment by Blaisorblade** [comment]
On CI, see my answer here: https://github.com/ocaml/camlp4/issues/150#issuecomment-489215833

Separately, I suspect the log in the OP can't be due to Homebrew, unlike on CI. camlp4 must be installed together with ocaml, and the `.opam/4.07.1+flambda` in the log:
```
/Users/mgree/.opam/4.07.1+flambda/bin/ocamlfind ocamldep -package bigarray -package bytes -package unix -syntax camlp4o -modules src/pa_have.ml > src/pa_have.ml.depends
```
suggests (weakly) you're using OCaml `4.07.1+flambda`, not Homebrew's. Then I think you should use a corresponding camlp4, which Homebrew won't provide.
