### ISSUE TITLE
can't you get rid of the camlp4 dependency?

### ISSUE THREAD

**Issue by UnixJunkie** [ygrek/extunix#35]
I thought camlp4 is a deprecated thing.

**Comment by ygrek** [comment]
duplicate #5

**Comment by UnixJunkie** [comment]
But this is not released, right?

**Comment by UnixJunkie** [comment]
Please tell if you make a new release, I could update the opam package then, if you like.

**Comment by ygrek** [comment]
indeed
thanks for reminder
released https://github.com/ocaml/opam-repository/pull/15244
