### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by glondu** [ygrek/extunix#55]
We were hit by the buggy splice implementation in Debian. I fixed it independently:

https://salsa.debian.org/ocaml-team/ocaml-extunix/-/blob/39ebc84549641126e4a620b543d588a3f5900fee/debian/patches/0002-Fix-type-of-offset-arguments-to-splice.patch

and saw afterwards that it had already been fixed here in 199669120db60a8280c31aa89791bf3e40aa65c8.

It would be nice if a new release were made, so that everyone can benefit from this.

**Comment by MisterDA** [comment]
I've just tagged v0.4.2 and submitted it to the opam repository, but it'll need a new patch: we're using `X_val` macros (such as `String_val` or `Int_val`) inside `caml_enter_blocking_section`/`caml_leave_blocking_section`, and this is incorrect. I can inspect the library in a week or so, when I come back from a break.
